Add FullCalendar Widget Implementation with Nostr Integration
illuminodes/minions pull request #10
Opened 2024-11-01 17:19 UTC by rahat2134

Fix #2 - Full calender widget
## Changes ##

Added FullCalendar widget bindings and components
Implemented Nostr integration for calendar events
Added event creation and management functionality
Added toast notifications for user feedback

## Features ##

Full calendar view with month/week/day layouts
Event creation via click & drag
Event storage using Nostr notes (kind: 31924)
Real-time event synchronization via Nostr relay
Toast notifications for user actions

## Testing Done ##

Calendar view rendering
Event creation & display
View switching (month/week/day)
Nostr event broadcasting
Toast notifications

## Dependencies Added ##

FullCalendar CSS and JS (via CDN)

2024-11-02 00:05 UTC, 42Pupusas requested changes
Bindings and components look great, a few small details to review:

2024-11-02 00:05 UTC, 42Pupusas commented on src/widgets/full_calendar/test_component.rs
> +        use_effect_with((), move |_| {
Need to emit a `NostrSubscription` to the `relay_ctx` to listen to the necessary evnt kinds, currently not receiving anything:

![image](https://github.com/user-attachments/assets/6e14670d-3d3e-4a8a-9cc3-e9e3192039d1)

2024-11-02 00:05 UTC, 42Pupusas commented on src/widgets/full_calendar/component.rs
> +                    calendar_instance.add_or_replace_event(event.clone());
please make sure no unhandled results for `add_or_replace_event` uses

2024-11-02 00:05 UTC, 42Pupusas commented on src/widgets/full_calendar/full_calendar.rs
> +            self.add_calendar_event(event);
please no unused results for `add_callentdar_events`

2024-11-02 00:06 UTC, 42Pupusas commented
Also pushed some changes to the `browser_api` helpers today so please merge those changes in as well

2024-11-02 08:01 UTC, rahat2134 commented on src/widgets/full_calendar/full_calendar.rs
> +            self.add_calendar_event(event);
Done

2024-11-02 08:02 UTC, rahat2134 commented on src/widgets/full_calendar/component.rs
> +                    calendar_instance.add_or_replace_event(event.clone());
Done

2024-11-02 08:02 UTC, rahat2134 commented on src/widgets/full_calendar/test_component.rs
> +        use_effect_with((), move |_| {
Done

2024-11-02 08:03 UTC, rahat2134 commented
@42Pupusas PTAL! Try to implement your feedback. I think everything is working fine.

2024-11-03 16:06 UTC, 42Pupusas commented on src/widgets/full_calendar/component.rs
> +                    calendar_instance.add_or_replace_event(event.clone());
sorry to nitpick but theres still one unused result:

![image](https://github.com/user-attachments/assets/39596c2d-ec94-4485-a43f-0bcbecb0017b)


im trying to make sure we get no warnings when using `cargo check` with default `rust-analyzer` options

2024-11-03 16:09 UTC, rahat2134 commented on src/widgets/full_calendar/component.rs
> +                    calendar_instance.add_or_replace_event(event.clone());
oh, I am really sorry for that, It just slipped from my eyes. I will push the changes. It is so silly of me :(

2024-11-03 16:47 UTC, rahat2134 commented on src/widgets/full_calendar/component.rs
> +                    calendar_instance.add_or_replace_event(event.clone());
@42Pupusas , I hope it's fine now. PTAL, If anything else you want please let me know. Thanks :)

2024-11-05 04:15 UTC, rahat2134 commented
@42Pupusas If this is good to go, can we get this merged?

2024-11-05 15:10 UTC, 42Pupusas approved these changes

2024-11-05 15:11 UTC, merged