Add AG Grid WASM Bindings and Component Coverage #2
illuminodes/minions pull request #6
Opened 2024-10-24 06:20 UTC by rahat2134

## Description
Implemented AG Grid WASM bindings and Yew component integration with comprehensive coverage for simple table structures.

### Features Added
- WASM bindings for AG Grid core functionality
- Column definitions and configuration
- Grid options (pagination, row selection)
- Reusable Yew component
- Auto-sizing and refresh capabilities

### Implementation Details
1. AG Grid Bindings (`ag_grid.rs`):
   - Core grid creation and manipulation
   - Column definitions with customization options
   - Default column properties
   - Grid options configuration
   - Type-safe option builders

2. Yew Component (`component.rs`):
   - Reusable functional component
   - Props for data, columns, and configuration
   - Auto grid initialization and updates
   - Responsive layout support

### Files Changed
- `src/widgets/ag_grid/ag_grid.rs`
- `src/widgets/ag_grid/component.rs`
- `src/widgets/ag_grid/mod.rs`

### Features
- Simple table structures
- Initial option configurations
- Event handling
- Nostr integration ready

Closes #2

2024-10-24 06:22 UTC, rahat2134 commented
@42Pupusas Please take a look!

2024-10-24 06:47 UTC, rahat2134 commented
PTAL to this after this I will tackle others in the list...

2024-10-25 22:44 UTC, 42Pupusas commented
Hey @rahat2134  this bindings and helpers are looking great. 

Please note the bounty description in #2 includes: 

```
Demo of Yew functional components showcasing Nostr integration
```

A simple test component that puts kind 0 or 1 events in a table will suffice.

You can see an example of pulling notes from the relay pool in the code I committed today.

2024-10-26 14:26 UTC, rahat2134 commented
@42Pupusas PTAL! I have pushed the changes.

2024-10-27 00:24 UTC, 42Pupusas commented
Im  getting a browser panic when the table is created, can we make sure all the bindings are implemented correctly?

```
ag-grid-community.min.js:1 Uncaught TypeError: e.map is not a function
    at u.setRowData (ag-grid-community.min.js:1:1713)
    at p.setRowData (ag-grid-community.min.js:1:20629)
    at y.onRowDataUpdated (ag-grid-community.min.js:1:28291)
    at ag-grid-community.min.js:1:27064
    at ag-grid-community.min.js:1:43663
    at kg.wrapIncoming (ag-grid-community.min.js:1:669896)
    at ag-grid-community.min.js:1:43645
    at ag-grid-community.min.js:1:43703
    at Set.forEach (<anonymous>)
    at r (ag-grid-community.min.js:1:43552)

﻿```

2024-10-27 06:58 UTC, rahat2134 commented
@42Pupusas PTAL! Any more suggestions?

2024-10-27 17:57 UTC, 42Pupusas requested changes
Please check this comments @rahat2134

2024-10-27 17:57 UTC, 42Pupusas commented on src/widgets/ag_grid/test_component.rs
> +    // Convert notes to row data
The update of the notes to rows needs to happen in a `use_effect` or the thread will block and not update.

```
    yew::use_effect_with(relay_ctx.unique_notes.clone(), move |notes| {
         // Update the rows here
        || {
             // Cleanup logic here
        }
    });
```

2024-10-27 17:57 UTC, 42Pupusas commented on src/widgets/ag_grid/test_component.rs
> +    // Convert notes to row data
Notice the pool does not refresh the events when the table is rendered as it is blocking the thread.  

![image](https://github.com/user-attachments/assets/ae2a2367-79c4-4519-8197-9ea40303ee91)


Without table:

![image](https://github.com/user-attachments/assets/81484305-ac74-49b9-ae2e-664478c1db86)

2024-10-27 21:29 UTC, rahat2134 commented
@42Pupusas , Pushed the changes. PTAL!
<img width="1440" alt="Screenshot 2024-10-28 at 2 56 58 AM" src="https://github.com/user-attachments/assets/74ed4248-fc45-4e6c-9580-370e51ce4fb3">

2024-10-28 19:41 UTC, 42Pupusas approved these changes

2024-10-28 19:42 UTC, merged

2024-10-28 19:44 UTC, 42Pupusas commented
Everything looks and works great. Another great contribution @rahat2134 .

2024-10-30 08:23 UTC, rahat2134 commented
@42Pupusas, Is the transaction for this bounty completed?

2024-10-30 18:04 UTC, rahat2134 commented
@42Pupusas PTAL whenever you have some bandwidth.